config/routes.rb
Jetpack::Application.routes.draw do

  root to: 'users#welcome'
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get  '/register', to: 'users#new'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get  '/logout',   to: 'sessions#destroy'

  resources :users
  resources :skills
  resources :references
  resources :courses, except: [:destroy]
  resources :categories
  resources :user_skills
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :jobs
  resources :password_resets

  

end

app/models/job.rb
class Job < ActiveRecord::Base
  acts_as_taggable
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?


  #def bydistance
    
  #  distance = params[:something]
     
  #end


  # has_many :tags
  #has_many :job_tags
  #has_many :tags, through: :job_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_taggable

  has_many :references
  has_many :courses
  has_many :user_skills
  has_many :tags
  has_many :jobs
  #has_many :user_tags
  #has_many :tags, through: :user_tags
  has_secure_password

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  validates :username, presence: true, uniqueness: true
  before_validation {|user| user.email = email.downcase }
  validates :email, presence: true, uniqueness: true

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
    self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
before_action :require_user, only: [:new] 

  def index

    if params[:search].present? && params[:tag].present?
      @jobs = Job.near(params[:search], params[:miles]).tagged_with(params[:tag])

    elsif params[:search].present?
      @users = User.near(params[:search], params[:miles])
      @jobs = Job.near(params[:search], params[:miles])
      #@jobs = Job.near search && tagged_with params tag.
  
    elsif params[:tag]
      @users = User.tagged_with(params[:tag])
      @jobs = Job.tagged_with(params[:tag])
    else
      @users = User.all
      @jobs = Job.all
    end

  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
    @job.user_id = current_user.id

    if @job.save
      flash[:notice] = "New Job Saved"
      redirect_to job_path(id: current_user.id)
    else
      render :new
    end
  end

  def show
    @jobs = Job.all.where(user_id: params[:id])
    @job  = Job.find_by(id: params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:notice] = "Your Job post was updated"
      redirect_to job_path(id: current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to job_path(id: current_user.id)
  end


  private

  def job_params
    params.require(:job).permit!
  end

  

end

app/views/jobs/_form.html.erb
<%= form_for @job do |f|                %>
  <%= f.label      :company                %>
  <%= f.text_field :company                %>
  <br/>
  <%= f.label      :position                  %>
  <%= f.text_field :title                  %>
  <br/>
  <%= f.label           :address %>
  <%= f.text_field      :address %>

  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :latitude  %>
  
  <br/>
  <%= f.label      :salary %>
  <%= f.text_field :salary %>
  <br/>
  <br/>
  <%= f.text_area  :description, :class => 'ckeditor' %>
  <br/>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class='control-group'>
    <%#= f.label "Tags" %>
    <%#= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
    <%#= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <%# end %>
  </div>

  <%= f.submit @job.new_record? ? "Create Job" : "Update Job", class: 'btn btn-primary'    %>
<% end %>

app/views/jobs/edit.html.erb
Hello from edit job.

<%= render 'form' %>

app/views/jobs/index.html.erb
<% if current_user == nil || current_user.status == 'career/education' %>
Search our jobs. 

<%= form_tag jobs_path, :method => :get do %>
 <p>Search by company name, Keywords, or title<br>
    <%= text_field_tag :tag, params[:tag] %>
  </p>
<p>Search within (miles)<br>
    <%= text_field_tag :miles, params[:miles]  %><br>
    of (city, State)<br>
    <%= text_field_tag :search, params[:search] %><%#should be city/state %>
<br><br>   
    <%= submit_tag "Search", :name => nil %>
  </p>

<% end %>



<div id="tag_cloud">
  <% tag_cloud Job.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>


  <% @jobs.each do |job| %>
    <div class='well'>
      <h2><%= link_to job.title, job_path(:id => job.id) %></h2>
      <li>Company: <%= job.company %></li>
      <li>Salary: <%= job.salary %></li>
      <li><%= job.address %></li>
      <% if current_user != nil && job.user_id == current_user.id %>
        <li><%=link_to "Edit Job", edit_job_path(job)%></li>
      <% end %>
      <p>
        Tags: <%= raw job.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </p>
    </div>
  <% end %>


<% elsif current_user.status == 'Employer' %>


<%= form_tag jobs_path, :method => :get do %>
  <p>Search within (miles)
    <%= text_field_tag :miles, params[:miles]  %>
    of (city, State)
    <%= text_field_tag :search, params[:search] %>
   
    <%= submit_tag "Search Near", :name => nil %>
  </p>

<% end %>


  <h1>Search profiles</h1>
    <p>Click tags to filter results</p><br/>
  <div id="tag_cloud">
  <% tag_cloud User.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<%#= form_tag users_path, :method => 'get' do %>
  <%#<p>
    <%= text_field_tag :search, params[:search] %>
    <%#= submit_tag "Search", :name => nil %>
  <%#</p>
<% end %>

  <%#= form_tag users_path, :method => 'get' do %>
    <%# @tags.each do |tags| %>
      <%#<li><%#= check_box_tag "tag_id[]", tags.id %>
          <%#= tags.name %>
      <%#</li>
    <%# end %>
    <%#= submit_tag "Search" %>

  <%# end %>




  <% @users.each do |user| %>
    <% if user.status == 'career/education' %>
      <div class='well'>
        <li><%= link_to user.username, user_path(user) %></li>
        <p>Tags: <%= raw user.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
        </p>
      </div>
    <% end %>
  <% end %>



<% end %>

app/views/jobs/new.html.erb
<%= form_for @job do |f|                %>
  <%= f.label      :company                %>
  <%= f.text_field :company                %>
  <br/>
  <%= f.label      :position                  %>
  <%= f.text_field :title                  %>
  <br/>
  <%= f.label           :address %>
  <%= f.text_field      :address %>

  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :latitude  %>
  
  <br/>
  <%= f.label      :salary %>
  <%= f.text_field :salary %>
  <br/>
  <br/>
  <%= f.text_area  :description, :class => 'ckeditor' %>
  <br/>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>



  <%= f.submit @job.new_record? ? "Create Job" : "Update Job", class: 'btn btn-primary'    %>
<% end %>

app/views/jobs/show.html.erb
<% if current_user == nil || current_user.status == 'career/education' %>
  <%= @job.description.html_safe %>
  <%= link_to "Employer Library", user_skills_path(:id => @job.user_id) %>
<% elsif current_user.status == 'Employer' %>
  <% @jobs.each do |job| %>
    <div class='well'>
      <h2><%= job.title %></h2> <h4><%= link_to 'Edit', edit_job_path(:id => job.id) %></h4>
        <h4><%= button_to "Delete",  job, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{job.title}?" %></h4>

      <li>Company: <%= job.company %></li>
      <li>Salary: <%= job.salary %></li>
      <li><%= job.address %></li>
      ------------------------------------------------
      <%= job.description.html_safe %>
      <p>
        Tags: <%= raw job.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </p>
    </div>
  <% end %>
<% end %>




  
    