config/routes.rb
Jetpack::Application.routes.draw do

  root to: 'users#welcome'
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get  '/register', to: 'users#new'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get  '/logout',   to: 'sessions#destroy'

  resources :users
  resources :skills
  resources :references
  resources :courses, except: [:destroy]
  resources :categories
  resources :user_skills
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :jobs
  resources :password_resets

  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_taggable

  has_many :references
  has_many :courses
  has_many :user_skills
  has_many :tags
  has_many :jobs
  #has_many :user_tags
  #has_many :tags, through: :user_tags
  has_secure_password

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  validates :username, presence: true, uniqueness: true
  before_validation {|user| user.email = email.downcase }
  validates :email, presence: true, uniqueness: true

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
    self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  #if params[:tag_id]
  #  binding.pry
  #  @tags = Tag.all

    #@users = User.all.where(self.tags == params[:tag_id])
    #@users = User.includes(:tags).where('tags.id IN ?', params[:tag_id])
  #else
  #  binding.pry
  #  @tags = Tag.all
    @users = User.all
  #  binding.pry
  #end
  #@users = User.search(params[:search])
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)

  if @user.save
    # Deliver the signup email
    Notifier.send_signup_email(@user).deliver
    #UserMailer.registration_confirmation(@user).deliver
  session[:user_id] = @user.id
    if @user.status == 'career/education'
      flash[:notice] = "Glad to have you! To get started, why don't you add any college courses you have taken to your degree page?"
      redirect_to courses_path
    else
      flash[:notice] = 'Welcome! Feel free to search our user base and find a team member that fits your company culture.'
      redirect_to jobs_path
    end
  else
    flash[:error] = "This username/email might already be taken, sorry!"
    render :new
  end
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "Your Profile was updated"
    redirect_to user_skill_path
  else
    render :edit
  end
end

def show
  @user = User.find_by(id: params[:id])
end

def welcome
  @jobsize = Job.all.size
  @skillsize = Skill.all.size
  @jobs =   Job.all
  @jobs = @jobs.paginate(:page => params[:page], :per_page => 5)
  @skills = Skill.all
  @skills = @skills.paginate(:page => params[:page], :per_page => 5)
end


private


def user_params
  params.require(:user).permit!
end

end

app/views/users/edit.html.erb
<strong>Edit your profile.</strong>
<div class='well'>
  <%= form_for @user do |f| %>

  <div class='control-group'>
    <%= f.label      :username %><br/>
    <%= f.text_field :username %>
  </div>

  <br/>
  <div class='control-group'>
    <%= f.label      :email %><br/>
    <%= f.text_field :email %>
  </div>
  <br/>
  <div class='field'>
    <%= f.label :tag_list, "Tags (Separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <br/>

    <%= f.text_area  :profile, :class => 'ckeditor' %>

  <br/>

    <%= f.submit @user.new_record? ? "Register" : "Update User", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Search profiles</h1>

<%#= form_tag users_path, :method => 'get' do %>
  <%#<p>
    <%= text_field_tag :search, params[:search] %>
    <%#= submit_tag "Search", :name => nil %>
  <%#</p>
<% end %>

  <%#= form_tag users_path, :method => 'get' do %>
    <%# @tags.each do |tags| %>
      <%#<li><%#= check_box_tag "tag_id[]", tags.id %>
          <%#= tags.name %>
      <%#</li>
    <%# end %>
    <%#= submit_tag "Search" %>

  <%# end %>




  <% @users.each do |user| %>
    <div class='well'>
      <li><%= link_to user.username, user_path(user) %></li>
      <p>Tags: <%= raw user.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </p>
    </div>
  <% end %>



<br><br>

<div class='well'>

<p>I'm in a well!</p>

</div>

app/views/users/new.html.erb
<div class='pull-right'>
  <h2>Employers Register Here</h2>
<div class='well'>
  <%= form_for @user do |f| %>

  <div class='control-group'>
    <%= f.label      :username %><br/>
    <%= f.text_field :username %>
  </div>
  <br/>
  <div class='control-group'>
    <%= f.label      :email %><br/>
    <%= f.text_field :email %>
  </div>
  <br/>
  <div class='control-group'>
    <%= f.label     :address %><br/>
    <%= f.text_field :address %> <p>Just a zip code is fine. No need for a full address</p>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>
  </div>

  <br/>

  <div class='hidden'>
    <%= f.label      :user_status %>
    <%= f.select     :status, options_for_select(%w[Employer])%>
  </div>
  <br/>
  <div class='control-group'>
    <%= f.label          :password %><br/>
    <%= f.password_field :password %>
  </div>
    <br/>

  <div class='control-group'>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
    <br/>
    <%= f.submit @user.new_record? ? "Register" : "Update User", class: 'btn btn-success' %>
  <% end %>
</div>
</div>



<div class='pull-left'>
  <h3>Job seekers and students register here</h3>
<div class='well'>
  <%= form_for @user do |f| %>

  <div class='control-group'>
    <%= f.label      :username %><br/>
    <%= f.text_field :username %>
  </div>
  <br/>
  <div class='control-group'>
    <%= f.label      :email %><br/>
    <%= f.text_field :email %>
  </div>
  <br/>
  <div class='control-group'>
    <%= f.label     :address %><br/>
    <%= f.text_field :address %>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>
  </div>

  <br/>

  <div class='hidden'>
    
    <%= f.label      :user_status %>
    <%= f.select     :status, options_for_select(%w[career/education])%>
  </div>
  <br/>
  <div class='control-group'>
    <%= f.label          :password %><br/>
    <%= f.password_field :password %>
  </div>
    <br/>

  <div class='control-group'>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
    <br/>
  <div class='field'>
    <p>Tags describe you to employers.</p>
    <strong>For example: <br/>Registered Nurse, Food Card, Business degree, etc...</strong></p>
    <%= f.label :tag_list, "Tags (Separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <br/>
    <%= f.submit @user.new_record? ? "Register" : "Update User", class: 'btn btn-success' %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<h1>Welcome to <%=@user.username%>'s profile.</h1>

<h3>Click on the links below to learn more about <%=@user.username%></h3>

<%= link_to "#{@user.username}'s Degree progress", course_path(:id => @user.id) %><br/>
<%= link_to "#{@user.username}'s References",      references_path(:id => @user.id) %><br/>
<%= link_to "#{@user.username}'s Library", user_skills_path(:id => @user.id) %><br/>
<%= link_to "#{@user.username}'s Documents and resumes", resumes_path(:id => @user.id) %> <br/>
<%= link_to "#{@user.username}'s Profile", user_skill_path(:id => @user.id) %> <br/>

app/views/users/welcome.html.erb
<%# def wrap(s, width=78)
    s.gsub(/(.{1,#{width}})(\s+|\Z)/, "\\1<br>").html_safe
   end %>



<% if current_user == nil %>
  <form action="<%= register_path %>">
      <input type="submit" id= 'register_button' value="Register!">
  </form>
  <form action="<%= login_path %>">
      <input type="submit" id='register_button' value="Log in">
  </form>
  
  <form action="<%= new_job_path %>">
      <input type="submit" id='register_button' value="Post Job, 100% Free">
    </form>
  <br><br>
<% else %>
  <form action="<%= logout_path %>">
      <input type="submit" id='register_button' value="Log out">
  </form>
  <br><br>
<% end %>

<% if current_user == nil || current_user.status == 'career/education' %>
<div class='pull-right'>
  <h1>Job Openings</h1>

        <%= form_tag jobs_path, :method => :get do %>
 <p>Search by company name, Keywords, or title<br>
    <%= text_field_tag :tag, params[:tag] %>
  </p>
<p>Search within (miles)<br>
    <%= text_field_tag :miles, params[:miles]  %><br>
    of (city, State)<br>
    <%= text_field_tag :search, params[:search] %><%#should be city/state %>
<br><br>   
    <%= submit_tag "Search", :name => nil %>
  </p>

<% end %>





  
</div>

<% end %>


<div class='pull-left'>
  <h1>Learn a Skill</h1>

  <%= form_tag skills_path, :method => :get do %>
 <p>what do you want to learn?<br>(You can also click "Earn Skills" above to see a list)<br>
    <%= text_field_tag :tag, params[:tag] %>
  </p>
    <%= submit_tag "Search", :name => nil %>
  </p>

<% end %>



  <%#= render 'skills/list', cat: @skills %>
 
</div>