config/routes.rb
Jetpack::Application.routes.draw do

  root to: 'users#welcome'
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get  '/register', to: 'users#new'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get  '/logout',   to: 'sessions#destroy'

  resources :users
  resources :skills
  resources :references
  resources :courses, except: [:destroy]
  resources :categories
  resources :user_skills
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :jobs
  resources :password_resets

  

end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  belongs_to :user
  #belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
before_action :require_user, only: [:new]
def index
  if current_user == nil || current_user.status == 'career/education'
    @user_skills = UserSkill.all.where(user_id: params[:id])
  else
    @user_skills = UserSkill.all.where(user_id: params[:id])
  end
end

def new
 @skill = Skill.find_by(id: params[:skill_id])
  @user_skill = UserSkill.new :user_id => current_user, :title => @skill.title, :url => @skill.url, :description => @skill.description

 respond_to do |format|
    format.html # new.html.erb
    format.xml  { render :xml => @post }
  end
end

def create
  @user_skill = UserSkill.new(user_skill_params)
  @user_skill.user = current_user 
  if @user_skill.save
    flash[:notice] = "Saved!"
    redirect_to user_skills_path(current_user.id)
  end
end

#def show
#  @user_skills = UserSkill.all.where(user_id: current_user)

#end

def edit
  @user_skill = UserSkill.find_by(id: params[:id])
end

def show
  @user = User.find_by(id: params[:id])

  if current_user == nil || current_user.status == 'career/education'
    @user_skills = UserSkill.all.where(user_id: params[:id])
  else
    @user_skills = UserSkill.all.where(user_id: params[:id])
  end

end

def update
  @user_skill = UserSkill.find_by(id: params[:id])
  if @user_skill.update(user_skill_params)
    flash[:notice] = "Marked as complete!"
    redirect_to user_skills_path
  else
    render :edit
  end
end


private

def user_skill_params
params.require(:user_skill).permit!
end


end

app/views/user_skills/edit.html.erb
<%= @user_skill.title %>

<%= form_for @user_skill do |f|                %>
  <%= f.label  :progress %> <p>explain your experience with this course so far</p>
  <%= f.text_area :progress, rows: 10 %>

<br/><br/>

  <%= f.submit @user_skill.new_record? ? "Add to my library" : "Update Skill", class: 'btn btn-primary'    %>
<% end %>

app/views/user_skills/index.html.erb
<h1>Library</h1>
<ul>
  <% @user_skills.each do |skill| %>
      <li class='well'> <font size='5'><%= link_to skill.title, fix_url(skill.url), :target => '_blank' %></font>
        <br><strong>Description</strong><br>
        <%=skill.description%><br/>
        ----------------------------------------------------------------<br>
        <%=skill.progress%>
        <br/>
      <% if current_user != nil && current_user.id == params[:id].to_i %>
        <%= link_to 'Update progress', edit_user_skill_path(:id => skill.id) %>
      <% end %>
      </li>
  <% end %>
</ul>

app/views/user_skills/new.html.erb
<% if current_user.status == 'career/education' %>
  <h1>Describe what you are learning or have learned from this course</h1>
<% elsif current_user.status == 'Employer' %>
  <h3>Add this skill to your library to let prospective job candidates know you want to hire someone learning it. Give a brief explanation if you want.</h3>
<% end %>
<%= form_for @user_skill do |f|                %>
  <%= f.label      :title                %>
  <%= f.text_field :title                %>
  <br/>
  <%= f.label      :progress          %>
  <br/>
  <%= f.text_area  :progress, rows: 5 %>
  <br/>
  <%= f.hidden_field :url %>
  <%= f.hidden_field      :description %>


  <%= f.submit @user_skill.new_record? ? "Add to my library" : "Update Skill", class: 'btn btn-primary'    %>
<% end %>

app/views/user_skills/show.html.erb
<% if @user.profile != nil %>
<h1><%= @user.username%>'s Profile</h1>

<%= @user.profile.html_safe %>

  <ul>
    <% @user_skills.each do |skill| %>
        <li class='well'> <font size='5'><%= link_to skill.title, fix_url(skill.url), :target => '_blank' %></font>
          <br><strong>Description</strong><br>
          <%=skill.description%><br/>
          ----------------------------------------------------------------<br>
          <%=skill.progress%>
          <br/>
        <% if current_user != nil && current_user.id == params[:id].to_i %>
          <%= link_to 'Update progress', edit_user_skill_path(:id => skill.id) %>
        <% end %>
        </li>
    <% end %>
  </ul>



<% else %>
<h1><%= @user.username %> Has not set up a profile yet</h1>
  <% if current_user.status == 'career/education' %>
    set it up here: <%= link_to "setup profile", edit_user_path(current_user) %>
  <% end %>

<h2><%= @user.username %> is currently learning the following from our website:</h2>

  <ul>
    <% @user_skills.each do |skill| %>
        <li class='well'> <font size='5'><%= link_to skill.title, fix_url(skill.url), :target => '_blank' %></font>
          <br><strong>Description</strong><br>
          <%=skill.description%><br/>
          ----------------------------------------------------------------<br>
          <%=skill.progress%>
          <br/>
        <% if current_user != nil && current_user.id == params[:id].to_i %>
          <%= link_to 'Update progress', edit_user_skill_path(:id => skill.id) %>
        <% end %>
        </li>
    <% end %>
  </ul>

<% end %>