config/routes.rb
Jetpack::Application.routes.draw do

  root to: 'users#welcome'
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get  '/register', to: 'users#new'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get  '/logout',   to: 'sessions#destroy'

  resources :users
  resources :skills
  resources :references
  resources :courses, except: [:destroy]
  resources :categories
  resources :user_skills
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :jobs
  resources :password_resets

  

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  acts_as_taggable
  has_many :skill_categories
  has_many :categories, through: :skill_categories

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
before_action :require_user, except: [:index, :show]


def index
  if params[:tag].present?
    @skills = Skill.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5)
  else
    @skills = Skill.all.paginate(:page => params[:page], :per_page => 5)
  end
end

def new
@skill = Skill.new
end

def create
  @skill = Skill.new(skill_params)

  if @skill.save
    flash[:notice] = "New Skill saved"
    redirect_to skill_path(@skill)
  else
    render :new
  end
end

def edit
  @skill = Skill.find(params[:id])
end

def update
  @skill = Skill.find(params[:id])
  if @skill.update(skill_params)
    flash[:notice] = "Skill was updated"
    redirect_to skills_path
  else
    render :edit
  end
end

def show
end

def destroy
  @skill = Skill.find(params[:id])
  @skill.destroy
  redirect_to skill_path, notice: "Skill was destroyed"
end

private

def skill_params
params.require(:skill).permit!
end

end

app/views/skills/_form.html.erb
<%= form_for @skill do |f|                %>
  <%= f.label      :title                %><br/>
  <%= f.text_field :title                %>
  <br/>
  <%= f.label      :price                %><br/>
  <%= f.text_field :price                %><br/>
  <%= f.label      :url                  %><br/>
  <%= f.text_field :url                  %>
  <br/>
  <%= f.label      :banner               %><br/>
  <%= f.text_field :banner               %>
  <br/>
  <%= f.label      :description          %>
  <br/>
  <%= f.text_area  :description, rows: 5 %>
  <br/>
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>

  <div class='control-group'>
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <%= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <%= f.submit @skill.new_record? ? "Create Skill" : "Update Skill", class: 'btn btn-primary'    %>
<% end %>

app/views/skills/_list.html.erb
  <% cat.each do |skill| %>

    <div class='well'>  <font size='5'>
      
      <%= skill_or_banner(skill) %>
    </font>


      <small><%= link_to 'Add to My Library', new_user_skill_path(:skill_id => skill.id) %></small>
    <% if logged_in? && current_user.username == 'Curry' %>
      <%= button_to "Delete",  skill, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{skill.title}?" %>
      <%= link_to "Edit",    edit_skill_path(skill), class: "btn btn-info" %>
    <% end %>
    <br>
    <% if skill.banner.size != 0 %>
      <%=skill.banner.html_safe %>
    <% end %>
<br>
      <strong>Price: </strong><%=skill.price%>
<br>  <strong>Description</strong><br>
    <%= wrap(skill.description.to_s, 65) %>
  </div>

  <% end %>

app/views/skills/_skill.html.erb
<%= link_to skill.title, fix_url(skill.url), :target => '_blank' %>

app/views/skills/edit.html.erb
<h1>Edit a skill</h1><% if current_user.username == 'Curry' %> <p><%= link_to "Add new category", new_category_path %> </p> <% end %>

<%= render 'form' %>

app/views/skills/index.html.erb
<h1>Learn something and add it to your profile!</h1>

<%= form_tag skills_path, :method => :get do %>
 <p>Search for skills<br>
    <%= text_field_tag :tag, params[:tag] %>
  </p>
    <%= submit_tag "Search", :name => nil %>
  </p>

<% end %>

<div class='pull-left'>

  <%= render 'list', cat: @skills %>
</div>

<%= will_paginate @skills %>

app/views/skills/new.html.erb
<h1>Post a new skill</h1><% if current_user.username == 'Curry' %> <p><%= link_to "Add new category", new_category_path %> </p> <% end %>

<%= render 'form' %>